#! /bin/bash

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a Display state=floating
bspc rule -a jetbrains-studio state=floating
bspc rule -a Unity state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Spotify state=floating
bspc rule -a spotify state=floating

# Autostart
sh $HOME/.config/polybar/launch.sh &
wal --backend wal -i ~/wallpapers/wallpaper16.png &
[[ ! $(pidof -x picom) ]] && picom --config $HOME/.config/picom.conf &
pidof bspswallow || bspswallow &
synclient TapButton1=1 TapButton2=3 TapButton3=2 HorizTwoFingerScroll=1 CircularScrolling=1 SingleTapTimeout=210 PalmDetect=1 PalmMinz=150 PalmMinWidth=5 &
xbindkeys1
$HOME/.custom_scripts/cleanfullscreen
#clipmenud
